### ISSUE TITLE
execute: ValueError: (<class 'int'>,) is not callable 

### ISSUE THREAD

**Issue by andreas-bulling** [kdschlosser/UPNP_Device#11]
```
python3 -m UPNP_Device --execute UPNPObject.RenderingControl.GetVolume --InstanceID 0 192.168.178.60                                 (develop✱)
Finding UPNP Devices please wait........
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/andreas/Desktop/UPNP_Device/UPNP_Device/__main__.py", line 232, in <module>
    main()
  File "/Users/andreas/Desktop/UPNP_Device/UPNP_Device/__main__.py", line 178, in main
    required=True
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/argparse.py", line 1358, in add_argument
    raise ValueError('%r is not callable' % (type_func,))
ValueError: (<class 'int'>,) is not callable
```

**Comment by kdschlosser** [comment]
OH I forgot to change that..

**Comment by andreas-bulling** [comment]
```
python3 -m UPNP_Device --execute UPNPObject.RenderingControl.GetVolume --InstanceID 0 192.168.178.60                                 (develop✱)
Traceback (most recent call last):
  File "/Users/andreas/Desktop/UPNP_Device/UPNP_Device/upnp_class.py", line 8, in <module>
    urlparse = __import__('urlparse').urlparse
ModuleNotFoundError: No module named 'urlparse'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/andreas/Desktop/UPNP_Device/UPNP_Device/__init__.py", line 14, in <module>
    from .listen import listen # NOQA
  File "/Users/andreas/Desktop/UPNP_Device/UPNP_Device/listen.py", line 8, in <module>
    from .upnp_class import UPNPObject
  File "/Users/andreas/Desktop/UPNP_Device/UPNP_Device/upnp_class.py", line 10, in <module>
    url_parse = __import__('urllib.parse').urlparse
AttributeError: module 'urllib' has no attribute 'urlparse'
```

**Comment by andreas-bulling** [comment]
After changing to python2 and installing missing dependencies I see:

```
python -m UPNP_Device --execute UPNPObject.RenderingControl.GetVolume --InstanceID 0 192.168.178.60                                  (develop✱)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/andreas/Desktop/UPNP_Device/UPNP_Device/__main__.py", line 91, in do
    args.dump
  File "UPNP_Device/__init__.py", line 20, in discover
    yield UPNPObject(addr, locations, dump)
  File "UPNP_Device/instance_singleton.py", line 11, in __call__
    super(InstanceSingleton, cls).__call__(id, *args)
  File "UPNP_Device/upnp_class.py", line 91, in __init__
    control_url = control_url.text.replace(url, '')
AttributeError: 'str' object has no attribute 'text'
```

**Comment by raydog153** [comment]
Bug with line 'control_url = control_url.text.replace(url, '')' calling text method. Try removing that.

Also for GetVolume you will need to supply '--Channel Master'. I have this working:
```
python upnp_device --execute UPNPObject.RenderingControl.GetVolume --InstanceID 0 --Channel Master 192.168.1.11
Finding UPNP Devices please wait.........
CurrentVolume: 12
```

**Comment by andreas-bulling** [comment]
it's slow but it works. I am really looking forward to when all of the controls works in HA :)

**Comment by kdschlosser** [comment]
well you are having it do the discover each and every single time.

    python upnp_device --timeout 3 --execute UPNPObject.RenderingControl.GetVolume --InstanceID 0 --Channel Master 192.168.1.11


give that a try and see how goes

**Comment by kdschlosser** [comment]
once you get everything up and running as a library the discovery process will only happen a single time. when you start the program. that is what takes the most amount of time. using that timeout you can set how long to search for. this can help speed things up. but there is going to be a threshold where it will not be able to find the device.
