### ISSUE TITLE
Missing data type for 'long'

### ISSUE THREAD

**Issue by raydog153** [kdschlosser/UPNP_Device#13]
In one XML file I have data type as '<dataType>long</dataType>', and this causes exception:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/rboutotte/samsungtv/UPNP_Device/upnp_device/__main__.py", line 91, in do
    args.dump
  File "/usr/local/lib/python2.7/site-packages/UPNP_Device-0.1.0b0-py2.7.egg/UPNP_Device/__init__.py", line 20, in discover
    yield UPNPObject(addr, locations, dump)
  File "/usr/local/lib/python2.7/site-packages/UPNP_Device-0.1.0b0-py2.7.egg/UPNP_Device/instance_singleton.py", line 11, in __call__
    super(InstanceSingleton, cls).__call__(id, *args)
  File "/usr/local/lib/python2.7/site-packages/UPNP_Device-0.1.0b0-py2.7.egg/UPNP_Device/upnp_class.py", line 102, in __init__
    dump=dump
  File "/usr/local/lib/python2.7/site-packages/UPNP_Device-0.1.0b0-py2.7.egg/UPNP_Device/service.py", line 104, in __init__
    state_variable = StateVariable(state_variable)
  File "/usr/local/lib/python2.7/site-packages/UPNP_Device-0.1.0b0-py2.7.egg/UPNP_Device/data_type.py", line 48, in __init__
    self.data_type = data_type_classes[data_type]
KeyError: 'long'
```

**Comment by kdschlosser** [comment]
let me check the UPNP spec

**Comment by kdschlosser** [comment]
http://upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v2.0.pdf

page 59 is where the data types start. 

no long listed...
