### ISSUE TITLE
Can't assign requested address

### ISSUE THREAD

**Issue by andreas-bulling** [kdschlosser/UPNP_Device#2]
Hi,

I tried the latest develop branch but see the following error on MacOS:

```
python3 -m UPNP_Device                                                                                                                (develop)
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/andreas/Desktop/UPNP_Device/UPNP_Device/discover.py", line 164, in do
    sock = send_to(local_address)
  File "/Users/andreas/Desktop/UPNP_Device/UPNP_Device/discover.py", line 160, in send_to
    sock.sendto(ssdp_packet.encode('utf-8'), (destination, 1900))
OSError: [Errno 49] Can't assign requested address
```

**Comment by kdschlosser** [comment]
directly run the discover file. this will only spit out the SSDP packets. but it will also enable deebug logging for the discover process.

**Comment by andreas-bulling** [comment]
that works but what shall I log and send to you?

**Comment by kdschlosser** [comment]
whatever was printed out to the screen

**Comment by andreas-bulling** [comment]
```
SSDP: 192.168.178.60 found LOCATION: http://192.168.178.60:7678/nservice/
SSDP: 192.168.178.60 found ST: upnp:rootdevice
SSDP: 192.168.178.60
M-SEARCH * HTTP/1.1
ST: upnp:rootdevice
MAN: "ssdp:discover"
HOST: 239.255.255.250:1900
MX: 1
Content-Length: 0


SSDP: 192.168.178.60 found LOCATION: http://192.168.178.60:7677/MainTVServer2/
SSDP: 192.168.178.60 found ST: upnp:rootdevice
SSDP: 192.168.178.60 found LOCATION: http://192.168.178.60:7677/MainTVServer2/
SSDP: 192.168.178.60 found ST: upnp:rootdevice
SSDP: 192.168.178.60 found LOCATION: http://192.168.178.60:7678/nservice/
SSDP: 192.168.178.60 found ST: upnp:rootdevice
SSDP: 192.168.178.60 found LOCATION: http://192.168.178.60:7677/MainTVServer2/
SSDP: 192.168.178.60 found ST: upnp:rootdevice
SSDP: 192.168.178.60 found LOCATION: http://192.168.178.60:7678/nservice/
SSDP: 192.168.178.60 found ST: upnp:rootdevice
SSDP: 192.168.178.60 found LOCATION: http://192.168.178.60:7677/MainTVServer2/
SSDP: 192.168.178.60 found ST: upnp:rootdevice
SSDP: 192.168.178.60 found LOCATION: http://192.168.178.60:7678/nservice/
SSDP: 192.168.178.60 found ST: upnp:rootdevice
SSDP: 192.168.178.60 found LOCATION: http://192.168.178.60:7676/rcr/
SSDP: 192.168.178.60 found ST: upnp:rootdevice
SSDP: 192.168.178.60 found LOCATION: http://192.168.178.60:7676/rcr/
SSDP: 192.168.178.60 found ST: upnp:rootdevice
SSDP: 192.168.178.60 found LOCATION: http://192.168.178.60:7676/rcr/
SSDP: 192.168.178.60 found ST: upnp:rootdevice
SSDP: 192.168.178.60 found LOCATION: http://192.168.178.60:7677/MainTVServer2/
SSDP: 192.168.178.60 found ST: upnp:rootdevice
SSDP: 192.168.178.60 found LOCATION: http://192.168.178.60:9197/dmr
SSDP: 192.168.178.60 found ST: upnp:rootdevice
SSDP: 192.168.178.60 - > b'HTTP/1.1 200 OK\r\nCACHE-CONTROL: max-age=1800\r\nDATE: Wed, 23 Jan 2019 07:42:39 GMT\r\nEXT: \r\nLOCATION: http://192.168.178.60:9197/dmr\r\nSERVER: SHP, UPnP/1.0, Samsung UPnP SDK/1.0\r\nST: upnp:rootdevice\r\nUSN: uuid:7da367fa-0b70-491b-894b-8d672cc2b316::upnp:rootdevice\r\nContent-Length: 0\r\n\r\n'
SSDP: 192.168.178.60 found LOCATION: http://192.168.178.60:9197/dmr
SSDP: 192.168.178.60 - > b'HTTP/1.1 200 OK\r\nCACHE-CONTROL: max-age=1800\r\nDATE: Wed, 23 Jan 2019 07:42:39 GMT\r\nEXT: \r\nLOCATION: http://192.168.178.60:9197/dmr\r\nSERVER: SHP, UPnP/1.0, Samsung UPnP SDK/1.0\r\nST: upnp:rootdevice\r\nUSN: uuid:7da367fa-0b70-491b-894b-8d672cc2b316::upnp:rootdevice\r\nContent-Length: 0\r\n\r\n'
SSDP: 192.168.178.60 found LOCATION: http://192.168.178.60:9197/dmr
SSDP: 192.168.178.60 found ST: upnp:rootdevice
SSDP: 192.168.178.60 - > b'HTTP/1.1 200 OK\r\nCACHE-CONTROL: max-age=1800\r\nDATE: Wed, 23 Jan 2019 07:42:39 GMT\r\nEXT: \r\nLOCATION: http://192.168.178.60:9197/dmr\r\nSERVER: SHP, UPnP/1.0, Samsung UPnP SDK/1.0\r\nST: upnp:rootdevice\r\nUSN: uuid:7da367fa-0b70-491b-894b-8d672cc2b316::upnp:rootdevice\r\nContent-Length: 0\r\n\r\n'
SSDP: 192.168.178.60 found LOCATION: http://192.168.178.60:7676/rcr/
SSDP: 192.168.178.60 - > b'HTTP/1.1 200 OK\r\nCACHE-CONTROL: max-age=1800\r\nDATE: Wed, 23 Jan 2019 07:42:39 GMT\r\nEXT: \r\nLOCATION: http://192.168.178.60:9197/dmr\r\nSERVER: SHP, UPnP/1.0, Samsung UPnP SDK/1.0\r\nST: upnp:rootdevice\r\nUSN: uuid:7da367fa-0b70-491b-894b-8d672cc2b316::upnp:rootdevice\r\nContent-Length: 0\r\n\r\n'
SSDP: 192.168.178.60 found ST: upnp:rootdevice
SSDP: 192.168.178.60 found LOCATION: http://192.168.178.60:7676/rcr/
SSDP: 192.168.178.60 found ST: upnp:rootdevice

```

**Comment by kdschlosser** [comment]
ok so no worries on this I will have it fixed shortly.

**Comment by raydog153** [comment]
@andreas-bulling I had same issue as you and am on a Mac as well. My workaround is listed here: https://github.com/kdschlosser/samsungctl/issues/40#issuecomment-457174254

Has to do with including the loop back network interface.

**Comment by kdschlosser** [comment]
This issue is now fixed I am guessing. if you want to give it a try with the develop branch and see.

**Comment by raydog153** [comment]
This issue is fixed however introduced typo issue for method 'decod' should be 'decode' in service.py line 70 and upnp_class.py line 56.

**Comment by kdschlosser** [comment]
lol

**Comment by kdschlosser** [comment]
damned e key.

**Comment by kdschlosser** [comment]
OK it is fixed

**Comment by raydog153** [comment]
@kdschlosser  Agreed it is fixed. This issue can be closed, I can't since I did not open it.
