### ISSUE TITLE
Exception TypeError: write() argument must be str, not bytes

### ISSUE THREAD

**Issue by raydog153** [kdschlosser/UPNP_Device#3]
After recent changes in develop branch I am getting this error when running dump command:

Running: ```python3 upnp_device -vvvv --dump './dump' 192.168.1.11```
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "upnp_device/__main__.py", line 87, in do
    for device in UPNP_Device.discover(args.timeout, log_level, args.ips, args.dump):
  File "/usr/local/lib/python3.7/site-packages/UPNP_Device-0.1.0b0-py3.7.egg/UPNP_Device/__init__.py", line 20, in discover
    yield UPNPObject(addr, locations, dump)
  File "/usr/local/lib/python3.7/site-packages/UPNP_Device-0.1.0b0-py3.7.egg/UPNP_Device/instance_singleton.py", line 11, in __call__
    super(InstanceSingleton, cls).__call__(id, *args)
  File "/usr/local/lib/python3.7/site-packages/UPNP_Device-0.1.0b0-py3.7.egg/UPNP_Device/upnp_class.py", line 59, in __init__
    f.write(response.content)
TypeError: write() argument must be str, not bytes
```

**Comment by raydog153** [comment]
This is working with python 2.7, so issue is related to python3 only. When I dump the response that is trying to be written out to file it is showing as bytes per stack trace:
```
b'<?xml version="1.0"?>\n<root xmlns=\'urn:schemas-upnp-org:device-1-0\' xmlns:sec=\'http://www.sec.co.kr/dlna\' xmlns:dlna=\'urn:schemas-dlna-org:device-1-0\'>\n <specVersion>\n  <major>1</major>\n  <minor>0</minor>\n </specVersion>\n <device>\n  <deviceType>urn:samsung.com:device:RemoteControlReceiver:1</deviceType>\n  <friendlyName>[TV]Samsung LED40</friendlyName>\n  <manufacturer>Samsung Electronics</manufacturer>\n  <manufacturerURL>http://www.samsung.com/sec</manufacturerURL>\n  <modelDescription>Samsung TV RCR</modelDescription>\n  <modelName>UN40H5203</modelName>\n  <modelNumber>1.0</modelNumber>\n  <modelURL>http://www.samsung.com/sec</modelURL>\n  <serialNumber>20090804RCR</serialNumber>\n  <UDN>uuid:08f0d180-0096-1000-82d5-84a46658d4ef</UDN>\n  <sec:deviceID>2DCL6GDVYAKIC</sec:deviceID>\n  <sec:ProductCap>Resolution:1920X1080,ImageZoom,ImageRotate,Y2014,ENC</sec:ProductCap>\n  <serviceList>\n   <service>\n    <serviceType>urn:samsung.com:service:MultiScreenService:1</serviceType>\n    <serviceId>urn:samsung.com:serviceId:MultiScreenService</serviceId>\n    <controlURL>/smp_5_</controlURL>\n    <eventSubURL>/smp_6_</eventSubURL>\n    <SCPDURL>/smp_4_</SCPDURL>\n   </service>\n  </serviceList>\n  <sec:Capabilities>\n   <sec:Capability name=\'samsung:multiscreen:1\' port=\'8001\' location=\'/ms/1.0/\'></sec:Capability>\n  </sec:Capabilities>\n </device>\n</root>\n'
```

**Comment by kdschlosser** [comment]
on that is not a problem... I will fix it.

**Comment by kdschlosser** [comment]
fixed.

**Comment by raydog153** [comment]
Fixed, closing.
