### ISSUE TITLE
Python3 decode issue

### ISSUE THREAD

**Issue by raydog153** [kdschlosser/UPNP_Device#5]
The last issue I saw on issue 4 wrt python 3 can be fixed by changing line 1435 in file data_type.py from
```
value = value.decode('utf-8')
```
to
```
value = value
```

**Comment by kdschlosser** [comment]
I need to see the error you were getting.

**Comment by kdschlosser** [comment]
give it a try now. I optimized the code in data_types.py and compressed it from 2100+ lines to around 750 lines.

**Comment by raydog153** [comment]
Well, now it is hanging and getting this error:
```
rboutotte@MacBook-Pro-2:~/samsungtv/UPNP_Device$ python3 upnp_device --execute UPNPObject.RenderingControl.GetVolume --InstanceID 0 --Channel Master 192.168.1.11
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "upnp_device/__main__.py", line 87, in do
    for device in UPNP_Device.discover(args.timeout, log_level, args.ips, args.dump):
  File "/usr/local/lib/python3.7/site-packages/UPNP_Device-0.1.0b0-py3.7.egg/UPNP_Device/__init__.py", line 20, in discover
    yield UPNPObject(addr, locations, dump)
  File "/usr/local/lib/python3.7/site-packages/UPNP_Device-0.1.0b0-py3.7.egg/UPNP_Device/instance_singleton.py", line 11, in __call__
    super(InstanceSingleton, cls).__call__(id, *args)
  File "/usr/local/lib/python3.7/site-packages/UPNP_Device-0.1.0b0-py3.7.egg/UPNP_Device/upnp_class.py", line 92, in __init__
    dump=dump
  File "/usr/local/lib/python3.7/site-packages/UPNP_Device-0.1.0b0-py3.7.egg/UPNP_Device/service.py", line 52, in __init__
    response = requests.get(url + location)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'http//192.168.1.11:7676/smp_12_': No schema supplied. Perhaps you meant http://http//192.168.1.11:7676/smp_12_?
```

**Comment by raydog153** [comment]
So the issue looks to be around this code, which is similar to an issue I was about to file WRT other non SamsungTv UNPN devices...
```python
        location = location.replace(url, '')
        location = location.replace('//', '/')
        response = requests.get(url + location)
```

Somehow there is missing ':' for scheme.

This is the hack I had added but for a different reason and does not fix this issue. What I was fixing here is that sometimes location does not have the preceding '/' when it needs too, so then request ends up like 'http://192.168.1.100:8090some_request.xml' and fails, so I had to add '/' but make sure to not add if already exist, so hack was to use replace in case of double:
```python
        location = location.replace('//', '/')
        print(url + ('/' + location).replace('//', '/'))
        response = requests.get(url + ('/' + location).replace('//', '/'))
```

**Comment by raydog153** [comment]
I think this code fixes the issue in service.py around line 52 (You will need to add urlparse import too of course):
```python
        parsed_url = urlparse(location)
        url = parsed_url.scheme + '//' + parsed_url.netloc
        response = requests.get(location)
```

**Comment by raydog153** [comment]
Nope, that is not correct fix....

The url input into the method is missing the ':' within scheme. 

Bah, so obvious in my face, it is the change you made in UPNP_Device/upnp_class.py line 37:
```python
url = parsed_url.scheme + '//' + parsed_url.netloc
```

**Comment by raydog153** [comment]
The last fix is working, along with my other change in service.py around line 54:
```
response = requests.get(url + ('/' + location).replace('//', '/'))
```

**Comment by kdschlosser** [comment]
you cannot do that either.

You have to remember that there is more then a single device that uses this library. one fix will booger it up for another device.

**Comment by kdschlosser** [comment]
do a dump I need to see the files.

**Comment by raydog153** [comment]
Yes, I have 8 UPNP devices and going thru each one to make sure they work, and when I fix something I try on other devices. All it is doing is adding '/' between url and location so that 'http://192.168.1.100:8090some_request.xml' does not happen.

Some devices have this:
```
<SCPDURL>/cdsSCPD.xml</SCPDURL>
```
Other devices have this:
```
<SCPDURL>dial_SCPD.xml</SCPDURL>
```

**Comment by raydog153** [comment]
Would you agree thou that at min this needs to be fixed:
```
url = parsed_url.scheme + '//' + parsed_url.netloc
```
To
```
url = parsed_url.scheme + '://' + parsed_url.netloc
```

**Comment by kdschlosser** [comment]
I do agree that does need to be fixed.

Do you know how to do a pull request. I want you to get the "credit" for repairs that you make.

these below are some of the examples of the SCPDURL that a device may use.. ones that I have come across so far. 

    <SCPDURL>/cdsSCPD.xml</SCPDURL>

    <SCPDURL>cdsSCPD.xml</SCPDURL>

    <SCPDURL>/path/cdsSCPD.xml</SCPDURL>

    <SCPDURL>path/cdsSCPD.xml</SCPDURL>

    <SCPDURL>//path/cdsSCPD.xml</SCPDURL>

    <SCPDURL>http://192.168.1.1:9999/path/cdsSCPD.xml</SCPDURL>

    <SCPDURL>http://192.168.1.1:9999/cdsSCPD.xml</SCPDURL>

**Comment by kdschlosser** [comment]
I have even seen the above where the location to the services xml file is in a path but the SDCPURL does not denote this path but it has to be added.

an example would be a SSDP packet that has a location of

    LOCATION: http://192.168.1.1:9999/path/some_file.xml

and then the service inside that file have SDCPURL's of 

    <SCPDURL>cdsSCPD.xml</SCPDURL>

and the path is a crap shoot at that point. it could be 

    http://192.168.1.1:9999/cdsSCPD.xml

or

    http://192.168.1.1:9999/path/cdsSCPD.xml

as I said no one follows the UPNP standard. so everything is all kinds of screwed up.

**Comment by raydog153** [comment]
Credit is overrated...lol. Yes I know how to do PR as git use is required for my day job. I thought I had to be given permission to create branch/PR etc..., if I have it or do not need it I can start to submit PR and tweak till consensus that it is correct fix.

Agree on the standard and use case your showed. In that case I would think you need logic to either try both or try one and if works move on, else try other one. I figure take things one step at a time, fix the simple things like missing '/', then fix how to handle whether path is correct or not.

**Comment by kdschlosser** [comment]
what you do is you fork the repository. pull the develop branch so you have it locally. and then make branches off the develop branch once you do a PR for a branch never make any modifications to that branch unless it pertains to that specific PR. from time to time do a forced pull against the my develop branch and then a push from your local to your fork .that will bring any changes into your fork from my repo.

I was unsure of how many variations we would find dealing with the SDCPURL. apparently it every possible combination. I am going to have to move the grabbing of the service into the device classes. this is going to make it easier to manage changing things about.

**Comment by raydog153** [comment]
I'll get my system setup tonight. We follow same process at work except the forking part.

**Comment by andreas-bulling** [comment]
@raydog153 if a commit fixes your problem it'd be good to close the issue. Thanks!

**Comment by kdschlosser** [comment]
once i merge the develop branch with the master branch all open issues that have been fixed will automatically be closed. so it really does not matter.

**Comment by andreas-bulling** [comment]
oh, I see, didn't know.

**Comment by kdschlosser** [comment]
tiz how we learn. if i add the word fixes and the number of the issue to the commit message when i update the code it add a marker to close the issue. you can see this is you hover the mouse over the word fixes above.
