### ISSUE TITLE
Exception around controlURL when empty

### ISSUE THREAD

**Issue by raydog153** [kdschlosser/UPNP_Device#6]
Here is the exception:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/rboutotte/samsungtv/UPNP_Device/upnp_device/__main__.py", line 87, in do
    for device in UPNP_Device.discover(args.timeout, log_level, args.ips, args.dump):
  File "/usr/local/lib/python2.7/site-packages/UPNP_Device-0.1.0b0-py2.7.egg/UPNP_Device/__init__.py", line 20, in discover
    yield UPNPObject(addr, locations, dump)
  File "/usr/local/lib/python2.7/site-packages/UPNP_Device-0.1.0b0-py2.7.egg/UPNP_Device/instance_singleton.py", line 11, in __call__
    super(InstanceSingleton, cls).__call__(id, *args)
  File "/usr/local/lib/python2.7/site-packages/UPNP_Device-0.1.0b0-py2.7.egg/UPNP_Device/upnp_class.py", line 81, in __init__
    control_url = service.find('controlURL').text.replace(url, '')
AttributeError: 'NoneType' object has no attribute 'replace'
```

This is the fix that is working for me around line 81 in file upnp_class.py from:
```python
                control_url = service.find('controlURL').text.replace(url, '')
```
To:
```python
                control_url = ''
                if service.find('controlURL').text is not None:
                    control_url = service.find('controlURL').text.replace(url, '')
```

**Comment by kdschlosser** [comment]
its a wee but deeper then that. because it affects every single function for that service.

I am curious as to why it is None. it shouldn't be.

if you do a dump I will give you each URL you will need to check. unless you know how to do it.

**Comment by raydog153** [comment]
I do not miss much once I become an expect in language. It is blank, here is dump of XML:
```xml
<?xml version="1.0"?>
<root xmlns="urn:schemas-upnp-org:device-1-0">
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<device>
<deviceType>urn:roku-com:device:player:1-0</deviceType>
<friendlyName>Master bedroom</friendlyName>
<manufacturer>Roku</manufacturer>
<manufacturerURL>http://www.roku.com/</manufacturerURL>
<modelDescription>Roku Streaming Player Network Media</modelDescription>
<modelName>Roku Streaming Stick+</modelName>
<modelNumber>3810X</modelNumber>
<modelURL>http://www.roku.com/</modelURL>
<serialNumber>YH001G188787</serialNumber>
<UDN>uuid:29600001-5c02-10e1-8073-c83a6bd59919</UDN>
<serviceList>
<service>
<serviceType>urn:roku-com:service:ecp:1</serviceType>
<serviceId>urn:roku-com:serviceId:ecp1-0</serviceId>
<controlURL></controlURL>
<eventSubURL></eventSubURL>
<SCPDURL>ecp_SCPD.xml</SCPDURL>
</service>
<service>
<serviceType>urn:dial-multiscreen-org:service:dial:1</serviceType>
<serviceId>urn:dial-multiscreen-org:serviceId:dial1-0</serviceId>
<controlURL></controlURL>
<eventSubURL></eventSubURL>
<SCPDURL>dial_SCPD.xml</SCPDURL>
</service>
</serviceList>
</device>
</root>
```

**Comment by raydog153** [comment]
Why can't the root URL be the control URL? Why does there need to be path?

**Comment by kdschlosser** [comment]
well this is what we are trying to has out.

I see where there is no text for the controlURL but it does list SCPDURL which is a location of the XML file that contains the list of functions for that service. I would be surprised if there are any functions defined in the service XML file

    http://IP_ADDRESS:PORT/ecp_SCPD.xml

since I do not know what the ip and port are you will have to key those in manually. they can be found in the SSDP.log file.

I would like to see the output from that URL please

**Comment by raydog153** [comment]
Here is the output http://IP_ADDRESS:PORT/ecp_SCPD.xml:
```xml
<?xml version="1.0"?>
<scpd xmlns="urn:schemas-upnp-org:service-1-0">
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<serviceStateTable>
<stateVariable sendEvents="no">
<name>A_ARG_TYPE_DeviceID</name>
<dataType>string</dataType>
</stateVariable>
</serviceStateTable>
</scpd>
```

Here is output of http://IP_ADDRESS:PORT/dial_SCPD.xml:
```xml
<?xml version="1.0"?>
<scpd xmlns="urn:schemas-upnp-org:service-1-0">
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<serviceStateTable>
<stateVariable sendEvents="no">
<name>A_ARG_TYPE_DeviceID</name>
<dataType>string</dataType>
</stateVariable>
</serviceStateTable>
</scpd>
```

**Comment by kdschlosser** [comment]
just like I said.. no functions.

But what I will do is if there is no controlURL I will pass ''. this way the service still gets built.

**Comment by raydog153** [comment]
Isn't that what my fix does?

**Comment by kdschlosser** [comment]
we needed to verify what we are dealing with first before we simply dive in head first. I am still thinking about what should be done. because in all reality if there are no functions then why bother building the service?. I am almost considering making a dummy service as a placeholder. so no errors can get thrown downstream because of the controlURL  not being valid. what I mean is if the file is actually populated with functions. then the control URL is a big ?.

the reason i say this is because POST is used to call a function. and get is used to grab the XML files.
this is an actual layout from a samsung TV.

    <controlURL>/smp_4_</controlURL>
    <eventSubURL>/smp_5_</eventSubURL>
    <SCPDURL>/smp_3_</SCPDURL>

what you see in the SCPDURL is a path not a file. and that path when a GET is used against it will hand out the file.

so this can be done as well. 

    <controlURL>/smp_3_</controlURL>
    <eventSubURL>/smp_5_</eventSubURL>
    <SCPDURL>/smp_3_</SCPDURL>

there is nothing to stop a dingding programmer from being lazy and doing

    <controlURL></controlURL>
    <eventSubURL>/smp_5_</eventSubURL>
    <SCPDURL>/smp_3_</SCPDURL>

and we are suppose to read our crystal ball and know that an empty controlURL actually means /smp_3_

this is yet another one of those pain UPNP issues because I do not know which way to specifically go. and there would be no concrete way of knowing what is right or wrong until a function gets called (if they exist)

**Comment by raydog153** [comment]
I get what you are saying. It may come down to be based on device. Seems to me for now better to continue to build out dummy service...may find we handle this better as we fix more so that some day down the road is is not dummy service but gets all filled in.

There is nothing stopping one from making an endpoint without a path work correct? May be the case for a lot of simple or non-standard devices. Not sure. I will admit I am not that familiar with UPNP, and networking standards is my weakest area.

**Comment by kdschlosser** [comment]
Networking is hands down the most complex thing to learn. the Cisco Engineer test is I believe the hardest test in existence. the only way to really know what is happening with networking is you have to look at it in binary, because of all of the bit shifting that is done with super netting and sub netting it is impossible to tell from looking at the IP address and the subnet mask.

**Comment by kdschlosser** [comment]
again the lack of a path in the controlURL can mean one of 2 things. There are no functions. Or the programmer was lazy and didn't put it in because the same path that is used for the SDCPURL handles both GET and POST. I guess what the right thing to do would be to check for the existence of an extension for the SDCPURL if there is no .xml on the end then we will assume that it should be used as the controlURL path. reason i say this will work is because if there is in fact no functions listed in the SDCPURL path. then the point is going to moot if it is wrong. because there are no functions to call that are going to use the path anyway.

**Comment by kdschlosser** [comment]
and if there is a .xml on the end to simply parse off the file leaving the path and use that
