### ISSUE TITLE
XMLNS parsing issue

### ISSUE THREAD

**Issue by raydog153** [kdschlosser/UPNP_Device#8]
All my home UPNP devices are discoverable now without issue except for my Belkin smart switch. This is the exception I get:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "upnp_device/__main__.py", line 87, in do
    for device in UPNP_Device.discover(args.timeout, log_level, args.ips, args.dump):
  File "/usr/local/lib/python3.7/site-packages/UPNP_Device-0.1.0b0-py3.7.egg/UPNP_Device/__init__.py", line 20, in discover
    yield UPNPObject(addr, locations, dump)
  File "/usr/local/lib/python3.7/site-packages/UPNP_Device-0.1.0b0-py3.7.egg/UPNP_Device/instance_singleton.py", line 11, in __call__
    super(InstanceSingleton, cls).__call__(id, *args)
  File "/usr/local/lib/python3.7/site-packages/UPNP_Device-0.1.0b0-py3.7.egg/UPNP_Device/upnp_class.py", line 102, in __init__
    dump=dump
  File "/usr/local/lib/python3.7/site-packages/UPNP_Device-0.1.0b0-py3.7.egg/UPNP_Device/service.py", line 93, in __init__
    root = strip_xmlns(root)
  File "/usr/local/lib/python3.7/site-packages/UPNP_Device-0.1.0b0-py3.7.egg/UPNP_Device/xmlns.py", line 21, in strip_xmlns
    strip_node(root)
  File "/usr/local/lib/python3.7/site-packages/UPNP_Device-0.1.0b0-py3.7.egg/UPNP_Device/xmlns.py", line 19, in strip_node
    strip_node(child)
  File "/usr/local/lib/python3.7/site-packages/UPNP_Device-0.1.0b0-py3.7.egg/UPNP_Device/xmlns.py", line 19, in strip_node
    strip_node(child)
  File "/usr/local/lib/python3.7/site-packages/UPNP_Device-0.1.0b0-py3.7.egg/UPNP_Device/xmlns.py", line 17, in strip_node
    n.tag = n.tag.replace(item, '')
AttributeError: 'cython_function_or_method' object has no attribute 'replace'
```

Here is the XML file it is trying to parse:

[setupservice.txt](https://github.com/kdschlosser/UPNP_Device/files/2796211/setupservice.txt)

**Comment by kdschlosser** [comment]
ok so I see you are using python 3.7.. try python 3.6 I am willing to bet the problem goes away Give it a try.

**Comment by raydog153** [comment]
Issue exist with python 2.7 as well. I can try 3.6 need to figure out how to better support multiple versions on my system I think.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/rboutotte/samsungtv/UPNP_Device/upnp_device/__main__.py", line 87, in do
    for device in UPNP_Device.discover(args.timeout, log_level, args.ips, args.dump):
  File "/usr/local/lib/python2.7/site-packages/UPNP_Device-0.1.0b0-py2.7.egg/UPNP_Device/__init__.py", line 20, in discover
    yield UPNPObject(addr, locations, dump)
  File "/usr/local/lib/python2.7/site-packages/UPNP_Device-0.1.0b0-py2.7.egg/UPNP_Device/instance_singleton.py", line 11, in __call__
    super(InstanceSingleton, cls).__call__(id, *args)
  File "/usr/local/lib/python2.7/site-packages/UPNP_Device-0.1.0b0-py2.7.egg/UPNP_Device/upnp_class.py", line 102, in __init__
    dump=dump
  File "/usr/local/lib/python2.7/site-packages/UPNP_Device-0.1.0b0-py2.7.egg/UPNP_Device/service.py", line 93, in __init__
    root = strip_xmlns(root)
  File "/usr/local/lib/python2.7/site-packages/UPNP_Device-0.1.0b0-py2.7.egg/UPNP_Device/xmlns.py", line 21, in strip_xmlns
    strip_node(root)
  File "/usr/local/lib/python2.7/site-packages/UPNP_Device-0.1.0b0-py2.7.egg/UPNP_Device/xmlns.py", line 19, in strip_node
    strip_node(child)
  File "/usr/local/lib/python2.7/site-packages/UPNP_Device-0.1.0b0-py2.7.egg/UPNP_Device/xmlns.py", line 19, in strip_node
    strip_node(child)
  File "/usr/local/lib/python2.7/site-packages/UPNP_Device-0.1.0b0-py2.7.egg/UPNP_Device/xmlns.py", line 17, in strip_node
    n.tag = n.tag.replace(item, '')
AttributeError: 'cython_function_or_method' object has no attribute 'replace'
```

**Comment by kdschlosser** [comment]
why is this happening all of a sudden??  No other time you have run this has this problem come up.

every single tag object is text it cannot be a function. Something has changed somewhere to cause this.
are you able to isolate a specific device that this issue is occurring with? does it work properly for other devices or is it happening with all devices?

**Comment by raydog153** [comment]
This was always there I beleive, I had not gotten around to debugging this UPNP device before but saw it, I was focused on getting UPNP working for SamsungTV first and now that those bugs are ironed out (at least for my model) I am working on other UPNP devices. This is belkin wemo switch.

You should be able to feed the xml data from file setupservice.txt to debug.

It is a recursion thing? I only say that since strip_node calls itself.

What if the tag doesn't exist for a node? I have not spent any time debugging this one as I need to understand what the code is doing more first.

**Comment by kdschlosser** [comment]
no it's not a recursion problem. I am not sure what the problem is. because every element in an XML tree is supposed to have a tag. that is the label of the element between the <> which is odd that the error is complaining about a function. I know that lxml uses C code to parse the  XML data because it is a bunch faster. so that function deal is probably happening because there is no tag. which would mean the XML is malformed in some way. the real question is why is it erroring like that if the XML is malformed. 

Do you mind manually following the XML paths and attaching the files??... use the SSDP to get the initial locations. then use the ip and port to finish up the beginning portions of the SDCPURL that you will find in the files when you follow the locations form the SSDP.

**Comment by raydog153** [comment]
I did attach the file in first comment (I can attach again but same details, or paste output) and looking at it in an IDE I do not see anything malformed, I'll look again. If you look at the code, the data gets dumped to a file before you parse the XML. 

I'll attach more debug info when I get the chance, after I validate the xml file more.

**Comment by kdschlosser** [comment]
are you sure that it is that file that the error is stemming from. because I see no errors either. that is the reason I wanted to get the whole structure. But if you are 100% certain that is the file that is being parsed. add a print statement for n.text in that function and see which one is specifically causing it. or at the very least we will know the element tag that is before the one that is causing the issue.

**Comment by raydog153** [comment]
Ok, here is curl output:
```
rboutotte@MacBook-Pro-2:~/Downloads$ curl -v http://192.168.1.64:49153/setupservice.xml
*   Trying 192.168.1.64...
* TCP_NODELAY set
* Connected to 192.168.1.64 (192.168.1.64) port 49153 (#0)
> GET /setupservice.xml HTTP/1.1
> Host: 192.168.1.64:49153
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< CONTENT-LENGTH: 4091
< CONTENT-TYPE: text/xml
< DATE: Fri, 25 Jan 2019 17:15:24 GMT
< LAST-MODIFIED: Sat, 01 Jan 2000 00:00:30 GMT
< SERVER: Unspecified, UPnP/1.0, Unspecified
< X-User-Agent: redsonic
< CONNECTION: close
<
<?xml version="1.0"?>
<scpd xmlns="urn:Belkin:service-1-0">

  <specVersion>
    <major>1</major>
    <minor>0</minor>
  </specVersion>

<actionList>
    <action>
        <name>GetApList</name>
        <argumentList>
         <argument>
         <retval />
         <name>ApList</name>
         <relatedStateVariable>ApList</relatedStateVariable>
         <direction>out</direction>
         </argument>
         </argumentList>
    </action>

    <action>
        <name>GetNetworkList</name>
        <argumentList>
         <argument>
         <retval />
         <name>NetworkList</name>
         <relatedStateVariable>NetworkList</relatedStateVariable>
         <direction>out</direction>
         </argument>
         </argumentList>
    </action>

    <action>
      <name>ConnectHomeNetwork</name>
      <argumentList>

         <argument>
           <name>ssid</name>
           <relatedStateVariable>ssid</relatedStateVariable>
           <direction>in</direction>
          </argument>

          <argument>
        <name>auth</name>
        <relatedStateVariable>auth</relatedStateVariable>
        <direction>in</direction>
        </argument>

       <argument>
             <name>password</name>
             <relatedStateVariable>password</relatedStateVariable>
             <direction>in</direction>
       </argument>

       <argument>
             <name>encrypt</name>
             <relatedStateVariable>encrypt</relatedStateVariable>
             <direction>in</direction>
       </argument>

       <argument>
             <name>channel</name>
             <relatedStateVariable>channel</relatedStateVariable>
             <direction>in</direction>
       </argument>

      </argumentList>

    </action>

        <action>
          <name>GetNetworkStatus</name>
          <argumentList>
             <argument>
               <retval />
               <name>NetworkStatus</name>
               <relatedStateVariable>NetworkStatus</relatedStateVariable>
               <direction>out</direction>
              </argument>
          </argumentList>
    </action>

    <action>
          <name>CloseSetup</name>
          <argumentList>
          </argumentList>
    </action>

	<action>
          <name>StopPair</name>
          <argumentList>
          </argumentList>
    </action>

</actionList>

  <serviceStateTable>

  <!-- connected, connecting, disconnected, time out error -->
  <stateVariable sendEvents="yes">
      <name>NetworkStatus</name>
      <dataType>string</dataType>
      <defaultValue>Disconnected</defaultValue>
    </stateVariable>
  <stateVariable sendEvents="yes">
	<name>PairingStatus</name>
      <dataType>string</dataType>
      <defaultValue>Connecting</defaultValue>
    </stateVariable>

    <stateVariable sendEvents="yes">
      <name>ApList</name>
      <dataType>string</dataType>
      <defaultValue></defaultValue>
    </stateVariable>

    <stateVariable sendEvents="yes">
      <name>NetworkList</name>
      <dataType>string</dataType>
      <defaultValue></defaultValue>
    </stateVariable>
    <stateVariable sendEvents="yes">
      <name>ssid</name>
      <dataType>string</dataType>
      <defaultValue></defaultValue>
    </stateVariable>

    <stateVariable sendEvents="yes">
      <name>auth</name>
      <dataType>string</dataType>
      <defaultValue></defaultValue>
    </stateVariable>

    <stateVariable sendEvents="yes">
      <name>password</name>
      <dataType>string</dataType>
      <defaultValue></defaultValue>
    </stateVariable>

    <stateVariable sendEvents="yes">
      <name>encrypt</name>
      <dataType>string</dataType>
      <defaultValue></defaultValue>
    </stateVariable>

    <stateVariable sendEvents="yes">
      <name>channel</name>
      <dataType>string</dataType>
      <defaultValue></defaultValue>
    </stateVariable>

    <stateVariable sendEvents="yes">
      <name>ssid</name>
      <dataType>string</dataType>
      <defaultValue></defaultValue>
    </stateVariable>

  </serviceStateTable>

  </scpd>
* Closing connection 0
```

**Comment by kdschlosser** [comment]
ahhh OK!!!! I know what it is!!

the comment line!!!

**Comment by raydog153** [comment]
And the issue is the comment within the XML file.

Extra printout using "print(n.tag)":
```
{urn:Belkin:service-1-0}serviceStateTable
<cyfunction Comment at 0x10b2acd10>
```

If you notice this comment is after start of tag serviceStateTable:
```
<!-- connected, connecting, disconnected, time out error -->
```

**Comment by raydog153** [comment]
You will find I am one of the best debuggers you will come across....

**Comment by kdschlosser** [comment]
and here is the code that will fix that problem. if you want to give it a go.

```python
def strip_xmlns(root):
    def iter_node(n):
        nsmap = n.nsmap
        for child in n:
            nsmap.update(iter_node(child))
        return nsmap

    xmlns = list('{' + item + '}' for item in iter_node(root).values())

    def strip_node(n):
        for item in xmlns:
            n.tag = n.tag.replace(item, '')
        for child in n[:]:
            try:
                strip_node(child)
            except AttributeError:
                n.remove(child)
    strip_node(root)

    return root
```

**Comment by raydog153** [comment]
Indeed it does fix it. lol...and onto the next issue. If you look this xml response does not have a 'device' node.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/rboutotte/samsungtv/UPNP_Device/upnp_device/__main__.py", line 87, in do
    for device in UPNP_Device.discover(args.timeout, log_level, args.ips, args.dump):
  File "/usr/local/lib/python2.7/site-packages/UPNP_Device-0.1.0b0-py2.7.egg/UPNP_Device/__init__.py", line 20, in discover
    yield UPNPObject(addr, locations, dump)
  File "/usr/local/lib/python2.7/site-packages/UPNP_Device-0.1.0b0-py2.7.egg/UPNP_Device/instance_singleton.py", line 11, in __call__
    super(InstanceSingleton, cls).__call__(id, *args)
  File "/usr/local/lib/python2.7/site-packages/UPNP_Device-0.1.0b0-py2.7.egg/UPNP_Device/upnp_class.py", line 78, in __init__
    node = root.find('device')
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by kdschlosser** [comment]
it is saying that the root node is None...
need to know where that is coming from.

it is either coming form the Service class or the UPNPObject class in the __init__ of either one.

in the UPNPObject add a print(location)

after this line of code.

    for location in locations:

and in the Service class add the same print after this line of code

    location = location.replace('//', '/')

**Comment by raydog153** [comment]
My bad, I applied the fix incorrectly, indentation was off and I missed it. Here is new error:

```
Service location url:
  /timesyncservice.xml
Request url:
  http://192.168.1.64:49153/timesyncservice.xml

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/rboutotte/samsungtv/UPNP_Device/upnp_device/__main__.py", line 87, in do
    for device in UPNP_Device.discover(args.timeout, log_level, args.ips, args.dump):
  File "/usr/local/lib/python2.7/site-packages/UPNP_Device-0.1.0b0-py2.7.egg/UPNP_Device/__init__.py", line 20, in discover
    yield UPNPObject(addr, locations, dump)
  File "/usr/local/lib/python2.7/site-packages/UPNP_Device-0.1.0b0-py2.7.egg/UPNP_Device/instance_singleton.py", line 11, in __call__
    super(InstanceSingleton, cls).__call__(id, *args)
  File "/usr/local/lib/python2.7/site-packages/UPNP_Device-0.1.0b0-py2.7.egg/UPNP_Device/upnp_class.py", line 105, in __init__
    dump=dump
  File "/usr/local/lib/python2.7/site-packages/UPNP_Device-0.1.0b0-py2.7.egg/UPNP_Device/service.py", line 84, in __init__
    f.write(content)
UnicodeEncodeError: 'ascii' codec can't encode character u'\ufeff' in position 0: ordinal not in range(128)
```

Xml response:
```
rboutotte@MacBook-Pro-2:~/Downloads$ curl -v http://192.168.1.64:49153/timesyncservice.xml
*   Trying 192.168.1.64...
* TCP_NODELAY set
* Connected to 192.168.1.64 (192.168.1.64) port 49153 (#0)
> GET /timesyncservice.xml HTTP/1.1
> Host: 192.168.1.64:49153
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< CONTENT-LENGTH: 1630
< CONTENT-TYPE: text/xml
< DATE: Fri, 25 Jan 2019 19:16:22 GMT
< LAST-MODIFIED: Sat, 01 Jan 2000 00:00:30 GMT
< SERVER: Unspecified, UPnP/1.0, Unspecified
< X-User-Agent: redsonic
< CONNECTION: close
<
<?xml version="1.0"?>
<scpd xmlns="urn:Belkin:service-1-0">
  <specVersion>
    <major>1</major>
    <minor>0</minor>
  </specVersion>

  <actionList>
    <action>
      <name>TimeSync</name>
      <argumentList>
         <argument>
		   <!-- UTC value, long -->
           <name>UTC</name>
           <relatedStateVariable>UTC</relatedStateVariable>
           <direction>in</direction>
          </argument>
         <argument>
           <name>TimeZone</name>
           <relatedStateVariable>TimeZone</relatedStateVariable>
           <direction>in</direction>
          </argument>
         <argument>
           <name>dst</name>
           <relatedStateVariable>dst</relatedStateVariable>
           <direction>in</direction>
          </argument>
		  <argument>
           <name>DstSupported</name>
           <relatedStateVariable>DstSupported</relatedStateVariable>
           <direction>in</direction>
          </argument>
      </argumentList>
    </action>

    <action>
      <name>GetTime</name>
    </action>

</actionList>

  <serviceStateTable>

        <stateVariable sendEvents="no">
        <!-- UTC seconds-->
      <name>UTC</name>
      <dataType>long</dataType>
      <defaultValue>0</defaultValue>
    </stateVariable>


    <stateVariable sendEvents="no">
      <name>TimeZone</name>
      <dataType>int</dataType>
      <defaultValue>0</defaultValue>
    </stateVariable>

	<stateVariable sendEvents="no">
      <name>dst</name>
      <dataType>Boolean</dataType>
      <defaultValue>0</defaultValue>
    </stateVariable>

  </serviceStateTable>

  </scpd>
```

**Comment by kdschlosser** [comment]
download and reinstall the library then run it. the line numbers do not line up.
