### ISSUE TITLE
Malformed URLs

### ISSUE THREAD

**Issue by andreas-bulling** [kdschlosser/UPNP_Device#9]
```
python3 -m UPNP_Device --dump logs 192.168.178.60                                                                                    (develop✱)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/andreas/Desktop/UPNP_Device/UPNP_Device/__main__.py", line 87, in do
    for device in UPNP_Device.discover(args.timeout, log_level, args.ips, args.dump):
  File "/Users/andreas/Desktop/UPNP_Device/UPNP_Device/__init__.py", line 20, in discover
    yield UPNPObject(addr, locations, dump)
  File "/Users/andreas/Desktop/UPNP_Device/UPNP_Device/instance_singleton.py", line 11, in __call__
    super(InstanceSingleton, cls).__call__(id, *args)
  File "/Users/andreas/Desktop/UPNP_Device/UPNP_Device/upnp_class.py", line 92, in __init__
    dump=dump
  File "/Users/andreas/Desktop/UPNP_Device/UPNP_Device/service.py", line 52, in __init__
    response = requests.get(url + location)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'http//192.168.178.60:7678dial.xml': No schema supplied. Perhaps you meant http://http//192.168.178.60:7678dial.xml?
```

**Comment by andreas-bulling** [comment]
There is also a ":" after "http" missing...

**Comment by kdschlosser** [comment]
there is.

**Comment by andreas-bulling** [comment]
fixed, thanks.
